# In _config.yml
title: Py4DataSci
author: Thomas Louf

execute:
  execute_notebooks: cache

only_build_toc_files: true

html:
  favicon: "_static/img/u1f40d.svg"
  use_repository_button: true
  home_page_in_navbar: false
  baseurl: "https://tlouf.github.io/Py4DataSci-course"

repository:
  url: https://github.com/TLouf/Py4DataSci-course
  path_to_book: "python-school"
  branch: "main"
