name: deploy-book

# Run this when the master or main branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    paths:
    - python-school/**

env:
  BOOK_DIR: python-school

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    # Install graphviz to draw Polars graphs.
    - name: Install graphviz
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: graphviz
        version: 1.0

    - name: Graphviz config
      run: |
        sudo dot -c

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt -r requirements-build.txt

    # (optional) Cache your executed notebooks between runs
    # if you have config:
    # execute:
    #   execute_notebooks: cache
    - name: cache executed notebooks
      uses: actions/cache@v4
      with:
        path: "$BOOK_DIR/_build/.jupyter_cache"
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build $BOOK_DIR

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "$BOOK_DIR/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
